// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTYdJjuXHl-p1yEjluuGUms99Ak_AEiJQ',
    appId: '1:507157517673:android:f83fa08aef59840ad199f8',
    messagingSenderId: '507157517673',
    projectId: 'goabsensi-c2366',
    databaseURL: 'https://goabsensi-c2366.firebaseio.com',
    storageBucket: 'goabsensi-c2366.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAym9EY2bXvtNalXv3pcrwhfMPuVZlpqvw',
    appId: '1:507157517673:ios:4ba2e8533d590295d199f8',
    messagingSenderId: '507157517673',
    projectId: 'goabsensi-c2366',
    databaseURL: 'https://goabsensi-c2366.firebaseio.com',
    storageBucket: 'goabsensi-c2366.appspot.com',
    iosClientId: '507157517673-hrcccttbeiabqo8falelhao7dbm6i3as.apps.googleusercontent.com',
    iosBundleId: 'com.example.goAbsensi',
  );
}
