import 'dart:async';
import 'dart:io';

import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:go_absensi/common/common.dart';
import 'package:go_absensi/models/models.dart';
import 'package:go_absensi/provider/provider.dart';
import 'package:go_absensi/services/services.dart';
import 'package:go_absensi/utils/utils.dart';
import 'package:go_absensi/widgets/widgets.dart';
import 'package:imei_plugin/imei_plugin.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';
import 'package:firebase_auth/firebase_auth.dart' as auth;
import 'package:qrscan/qrscan.dart' as scanner;
import 'package:timer_builder/timer_builder.dart';
import 'package:go_absensi/extensions/extensions.dart';
import 'package:url_launcher/url_launcher.dart';

part 'wrapper.dart';
part 'splash_screen.dart';
part 'login_screen.dart';
part 'register_screen.dart';
part 'upload_photo_screen.dart';
part 'main_screen.dart';
part 'success_screen.dart';
part 'dashboard_view.dart';
part 'presence_view.dart';
part 'check_in_screen.dart';
part 'check_out_screen.dart';
part 'history_screen.dart';
part 'permit_letter_screen.dart';
part 'letter_form_screen.dart';
part 'letter_detail_screen.dart';